### ISSUE TITLE
CouchbaseClusterSample not reporting - Error and <empty> entity name

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nri-couchbase#32]
#### CouchbaseClusterSample Not Reporting 

There are no values being reported for the CouchbaseClusterSample.

##### Configuration
```yaml
--- 
instances: 
  - 
    arguments: 
      enable_bucket_stats: true
      enable_buckets: true
      enable_cluster_and_nodes: true
      hostname: localhost
      password: rdrdrdrd
      port: 8091
      query_port: 8093
      timeout: 30
      use_ssl: false
      username: rd_rd_rd
    command: all_data
    labels:
        PARTITION: RD
        REGION: RD1
        PRODUCT: RD
        ENVIRONMENT: RD
        PROJECT: RD
        COMPONENT: RD
integration_name: com.newrelic.couchbase
```

#### Error Message
```text
time="2020-01-27T11:49:14-08:00" level=debug msg="Integration command wrote to stderr" instance= integration=com.newrelic.couchbase prefix=config/couchbase stderr="[ERR] Error running collection for collector '': entity name and type are required when defining one\n" working-dir=/var/db/newrelic-infra/newrelic-integrations
```

#### OS

- [x] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
